### ISSUE TITLE
Update script to convert single value fields to arrays

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/GBL-Schema-Update#2]
Some fields started out as only single value. When we added _sm to the end, that means they should become arrays.

**Comment by Ziiiiing** [comment]
Got it! The script will be fixed tomorrow. 😊

**Comment by Ziiiiing** [comment]
I noticed that there is one transformation from `solr_year_i` to `gbl_indexYear_im` recorded in the **crosswalk.csv**, and I remember that this field ending with `_im` is also marked as a multi-value one, which should also be converted to arrays, I guess.🧐

**Comment by karenmajewicz** [comment]
Yes- good catch!
