### ISSUE TITLE
btaa_aardvark_fixtures.csv - Missing ID value

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/GBL-Schema-Update#6]
Number 34, "Access Across America: Auto Data，2018" is missing an ID value (required) and does not import.

Took a while to troubleshoot this issue. Was this intentional? This edge case doesn't "error" in the application, so it's kinda a nice test of the current import design. We should probably "audit" the spreadsheet prior to running the import to point out any rows that won't be imported.

**Comment by karenmajewicz** [comment]
That is odd, because when I look at the CSV, I see the value of `f397d257-3587-4b8a-ab40-fdd06f865862` in the ID field for that record. Could there be something wrong with the CSV formatting on that row?

**Comment by ewlarson** [comment]
HMMMM... You are right! Google Sheets seems to be messing with me.
