### ISSUE TITLE
btaa_aardvark_fixtures.csv - duplicate row

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/GBL-Schema-Update#7]
Okok... been banging my head on this for a while. Something was amiss with testing this import. I have 74 import rows, but only 73 documents imported.

Turns out there is a duplicate record in this CSV file:
https://github.com/BTAA-Geospatial-Data-Project/GBL-Schema-Update/blob/main/btaa_aardvark_fixtures.csv#L16-L17

**Comment by karenmajewicz** [comment]
Oh no! I will delete.

**Comment by karenmajewicz** [comment]
OK, I deleted the second Indiana record
