### ISSUE TITLE
solr_documents_aardvark - solr_year_i

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/GBL-Schema-Update#8]
The Aardvark fixtures have solr_year_i and not [gbl_indexYear_i](https://docs.google.com/spreadsheets/d/1QQjUzRe8YdPGKK4h0GYoNPTow2zZ1f0KFA0zzZyHAsk/edit?ts=602d52f2#gid=438729461).

Maybe this is a mistake in the crosswalk.csv file here:
https://github.com/BTAA-Geospatial-Data-Project/GBL-Schema-Update/blob/main/crosswalk.csv#L11

Also! We made BTAA Aardvark fixtures with [gbl_indexYear_im](https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/feature/btaa-aardvark/test/fixtures/files/btaa_documents/b1g_access_rights_html_link.json#L52) (multiple value), but the Aardvark documentation suggests this should be singular and not multiple valued.

**Comment by karenmajewicz** [comment]
I think this discrepancy came from an unresolved question of whether or not GeoBlacklight (at least v.3.3) can handle multiple values in Index Year? This is something we want, but I wasn't sure if it would "break" the facets/widget?

**Comment by ewlarson** [comment]
Ah! In that situation, I'd say make the data you want and we'll make GBL work for our needs. Likely, a local override and a PR to merge that code into the GBL 4.0 development branch.

**Comment by karenmajewicz** [comment]
OK, thanks. I am going to update the GBL Aardvark documentation and clarify with everyone what the element should be.

**Comment by karenmajewicz** [comment]
Updated documentation
